//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("DrisionMVCFrameModel", "FK_Sys_R_Role_Action_SysAction", "SysAction", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Drision.MVCFrame.Model.SysAction), "Sys_R_Role_Action", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Drision.MVCFrame.Model.Sys_R_Role_Action), true)]
[assembly: EdmRelationshipAttribute("DrisionMVCFrameModel", "FK_Sys_R_Role_Action_SysRole", "SysRole", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Drision.MVCFrame.Model.SysRole), "Sys_R_Role_Action", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Drision.MVCFrame.Model.Sys_R_Role_Action), true)]
[assembly: EdmRelationshipAttribute("DrisionMVCFrameModel", "FK_Sys_R_User_Action_SysAction", "SysAction", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Drision.MVCFrame.Model.SysAction), "Sys_R_User_Action", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Drision.MVCFrame.Model.Sys_R_User_Action), true)]
[assembly: EdmRelationshipAttribute("DrisionMVCFrameModel", "FK_Sys_R_User_Action_SysUser", "SysUser", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Drision.MVCFrame.Model.SysUser), "Sys_R_User_Action", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Drision.MVCFrame.Model.Sys_R_User_Action), true)]
[assembly: EdmRelationshipAttribute("DrisionMVCFrameModel", "FK_Sys_R_User_Role_SysRole", "SysRole", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Drision.MVCFrame.Model.SysRole), "Sys_R_User_Role", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Drision.MVCFrame.Model.Sys_R_User_Role), true)]
[assembly: EdmRelationshipAttribute("DrisionMVCFrameModel", "FK_Sys_R_User_Role_SysUser", "SysUser", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Drision.MVCFrame.Model.SysUser), "Sys_R_User_Role", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Drision.MVCFrame.Model.Sys_R_User_Role), true)]

#endregion

namespace Drision.MVCFrame.Model
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class DrisionMVCFrameEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“DrisionMVCFrameEntities”部分中的连接字符串初始化新 DrisionMVCFrameEntities 对象。
        /// </summary>
        public DrisionMVCFrameEntities() : base("name=DrisionMVCFrameEntities", "DrisionMVCFrameEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DrisionMVCFrameEntities 对象。
        /// </summary>
        public DrisionMVCFrameEntities(string connectionString) : base(connectionString, "DrisionMVCFrameEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DrisionMVCFrameEntities 对象。
        /// </summary>
        public DrisionMVCFrameEntities(EntityConnection connection) : base(connection, "DrisionMVCFrameEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Sys_R_Role_Action> Sys_R_Role_Action
        {
            get
            {
                if ((_Sys_R_Role_Action == null))
                {
                    _Sys_R_Role_Action = base.CreateObjectSet<Sys_R_Role_Action>("Sys_R_Role_Action");
                }
                return _Sys_R_Role_Action;
            }
        }
        private ObjectSet<Sys_R_Role_Action> _Sys_R_Role_Action;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Sys_R_User_Action> Sys_R_User_Action
        {
            get
            {
                if ((_Sys_R_User_Action == null))
                {
                    _Sys_R_User_Action = base.CreateObjectSet<Sys_R_User_Action>("Sys_R_User_Action");
                }
                return _Sys_R_User_Action;
            }
        }
        private ObjectSet<Sys_R_User_Action> _Sys_R_User_Action;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Sys_R_User_Role> Sys_R_User_Role
        {
            get
            {
                if ((_Sys_R_User_Role == null))
                {
                    _Sys_R_User_Role = base.CreateObjectSet<Sys_R_User_Role>("Sys_R_User_Role");
                }
                return _Sys_R_User_Role;
            }
        }
        private ObjectSet<Sys_R_User_Role> _Sys_R_User_Role;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SysAction> SysAction
        {
            get
            {
                if ((_SysAction == null))
                {
                    _SysAction = base.CreateObjectSet<SysAction>("SysAction");
                }
                return _SysAction;
            }
        }
        private ObjectSet<SysAction> _SysAction;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SysGroup> SysGroup
        {
            get
            {
                if ((_SysGroup == null))
                {
                    _SysGroup = base.CreateObjectSet<SysGroup>("SysGroup");
                }
                return _SysGroup;
            }
        }
        private ObjectSet<SysGroup> _SysGroup;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SysRole> SysRole
        {
            get
            {
                if ((_SysRole == null))
                {
                    _SysRole = base.CreateObjectSet<SysRole>("SysRole");
                }
                return _SysRole;
            }
        }
        private ObjectSet<SysRole> _SysRole;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SysUser> SysUser
        {
            get
            {
                if ((_SysUser == null))
                {
                    _SysUser = base.CreateObjectSet<SysUser>("SysUser");
                }
                return _SysUser;
            }
        }
        private ObjectSet<SysUser> _SysUser;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Sys_R_Role_Action EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSys_R_Role_Action(Sys_R_Role_Action sys_R_Role_Action)
        {
            base.AddObject("Sys_R_Role_Action", sys_R_Role_Action);
        }
    
        /// <summary>
        /// 用于向 Sys_R_User_Action EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSys_R_User_Action(Sys_R_User_Action sys_R_User_Action)
        {
            base.AddObject("Sys_R_User_Action", sys_R_User_Action);
        }
    
        /// <summary>
        /// 用于向 Sys_R_User_Role EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSys_R_User_Role(Sys_R_User_Role sys_R_User_Role)
        {
            base.AddObject("Sys_R_User_Role", sys_R_User_Role);
        }
    
        /// <summary>
        /// 用于向 SysAction EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSysAction(SysAction sysAction)
        {
            base.AddObject("SysAction", sysAction);
        }
    
        /// <summary>
        /// 用于向 SysGroup EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSysGroup(SysGroup sysGroup)
        {
            base.AddObject("SysGroup", sysGroup);
        }
    
        /// <summary>
        /// 用于向 SysRole EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSysRole(SysRole sysRole)
        {
            base.AddObject("SysRole", sysRole);
        }
    
        /// <summary>
        /// 用于向 SysUser EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSysUser(SysUser sysUser)
        {
            base.AddObject("SysUser", sysUser);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DrisionMVCFrameModel", Name="Sys_R_Role_Action")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sys_R_Role_Action : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Sys_R_Role_Action 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="roleID">RoleID 属性的初始值。</param>
        /// <param name="actionID">ActionID 属性的初始值。</param>
        public static Sys_R_Role_Action CreateSys_R_Role_Action(global::System.Int32 id, global::System.Int32 roleID, global::System.Int32 actionID)
        {
            Sys_R_Role_Action sys_R_Role_Action = new Sys_R_Role_Action();
            sys_R_Role_Action.ID = id;
            sys_R_Role_Action.RoleID = roleID;
            sys_R_Role_Action.ActionID = actionID;
            return sys_R_Role_Action;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                OnRoleIDChanging(value);
                ReportPropertyChanging("RoleID");
                _RoleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleID");
                OnRoleIDChanged();
            }
        }
        private global::System.Int32 _RoleID;
        partial void OnRoleIDChanging(global::System.Int32 value);
        partial void OnRoleIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActionID
        {
            get
            {
                return _ActionID;
            }
            set
            {
                OnActionIDChanging(value);
                ReportPropertyChanging("ActionID");
                _ActionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActionID");
                OnActionIDChanged();
            }
        }
        private global::System.Int32 _ActionID;
        partial void OnActionIDChanging(global::System.Int32 value);
        partial void OnActionIDChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DrisionMVCFrameModel", "FK_Sys_R_Role_Action_SysAction", "SysAction")]
        public SysAction SysAction
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysAction>("DrisionMVCFrameModel.FK_Sys_R_Role_Action_SysAction", "SysAction").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysAction>("DrisionMVCFrameModel.FK_Sys_R_Role_Action_SysAction", "SysAction").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SysAction> SysActionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysAction>("DrisionMVCFrameModel.FK_Sys_R_Role_Action_SysAction", "SysAction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SysAction>("DrisionMVCFrameModel.FK_Sys_R_Role_Action_SysAction", "SysAction", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DrisionMVCFrameModel", "FK_Sys_R_Role_Action_SysRole", "SysRole")]
        public SysRole SysRole
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysRole>("DrisionMVCFrameModel.FK_Sys_R_Role_Action_SysRole", "SysRole").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysRole>("DrisionMVCFrameModel.FK_Sys_R_Role_Action_SysRole", "SysRole").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SysRole> SysRoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysRole>("DrisionMVCFrameModel.FK_Sys_R_Role_Action_SysRole", "SysRole");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SysRole>("DrisionMVCFrameModel.FK_Sys_R_Role_Action_SysRole", "SysRole", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DrisionMVCFrameModel", Name="Sys_R_User_Action")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sys_R_User_Action : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Sys_R_User_Action 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="userID">UserID 属性的初始值。</param>
        /// <param name="actionID">ActionID 属性的初始值。</param>
        public static Sys_R_User_Action CreateSys_R_User_Action(global::System.Int32 id, global::System.Int32 userID, global::System.Int32 actionID)
        {
            Sys_R_User_Action sys_R_User_Action = new Sys_R_User_Action();
            sys_R_User_Action.ID = id;
            sys_R_User_Action.UserID = userID;
            sys_R_User_Action.ActionID = actionID;
            return sys_R_User_Action;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActionID
        {
            get
            {
                return _ActionID;
            }
            set
            {
                OnActionIDChanging(value);
                ReportPropertyChanging("ActionID");
                _ActionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActionID");
                OnActionIDChanged();
            }
        }
        private global::System.Int32 _ActionID;
        partial void OnActionIDChanging(global::System.Int32 value);
        partial void OnActionIDChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DrisionMVCFrameModel", "FK_Sys_R_User_Action_SysAction", "SysAction")]
        public SysAction SysAction
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysAction>("DrisionMVCFrameModel.FK_Sys_R_User_Action_SysAction", "SysAction").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysAction>("DrisionMVCFrameModel.FK_Sys_R_User_Action_SysAction", "SysAction").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SysAction> SysActionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysAction>("DrisionMVCFrameModel.FK_Sys_R_User_Action_SysAction", "SysAction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SysAction>("DrisionMVCFrameModel.FK_Sys_R_User_Action_SysAction", "SysAction", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DrisionMVCFrameModel", "FK_Sys_R_User_Action_SysUser", "SysUser")]
        public SysUser SysUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysUser>("DrisionMVCFrameModel.FK_Sys_R_User_Action_SysUser", "SysUser").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysUser>("DrisionMVCFrameModel.FK_Sys_R_User_Action_SysUser", "SysUser").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SysUser> SysUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysUser>("DrisionMVCFrameModel.FK_Sys_R_User_Action_SysUser", "SysUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SysUser>("DrisionMVCFrameModel.FK_Sys_R_User_Action_SysUser", "SysUser", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DrisionMVCFrameModel", Name="Sys_R_User_Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sys_R_User_Role : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Sys_R_User_Role 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="userID">UserID 属性的初始值。</param>
        /// <param name="roleID">RoleID 属性的初始值。</param>
        public static Sys_R_User_Role CreateSys_R_User_Role(global::System.Int32 id, global::System.Int32 userID, global::System.Int32 roleID)
        {
            Sys_R_User_Role sys_R_User_Role = new Sys_R_User_Role();
            sys_R_User_Role.ID = id;
            sys_R_User_Role.UserID = userID;
            sys_R_User_Role.RoleID = roleID;
            return sys_R_User_Role;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                OnRoleIDChanging(value);
                ReportPropertyChanging("RoleID");
                _RoleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleID");
                OnRoleIDChanged();
            }
        }
        private global::System.Int32 _RoleID;
        partial void OnRoleIDChanging(global::System.Int32 value);
        partial void OnRoleIDChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DrisionMVCFrameModel", "FK_Sys_R_User_Role_SysRole", "SysRole")]
        public SysRole SysRole
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysRole>("DrisionMVCFrameModel.FK_Sys_R_User_Role_SysRole", "SysRole").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysRole>("DrisionMVCFrameModel.FK_Sys_R_User_Role_SysRole", "SysRole").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SysRole> SysRoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysRole>("DrisionMVCFrameModel.FK_Sys_R_User_Role_SysRole", "SysRole");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SysRole>("DrisionMVCFrameModel.FK_Sys_R_User_Role_SysRole", "SysRole", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DrisionMVCFrameModel", "FK_Sys_R_User_Role_SysUser", "SysUser")]
        public SysUser SysUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysUser>("DrisionMVCFrameModel.FK_Sys_R_User_Role_SysUser", "SysUser").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysUser>("DrisionMVCFrameModel.FK_Sys_R_User_Role_SysUser", "SysUser").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SysUser> SysUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SysUser>("DrisionMVCFrameModel.FK_Sys_R_User_Role_SysUser", "SysUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SysUser>("DrisionMVCFrameModel.FK_Sys_R_User_Role_SysUser", "SysUser", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DrisionMVCFrameModel", Name="SysAction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SysAction : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SysAction 对象。
        /// </summary>
        /// <param name="actionID">ActionID 属性的初始值。</param>
        /// <param name="requestUrl">RequestUrl 属性的初始值。</param>
        /// <param name="requestHttpType">RequestHttpType 属性的初始值。</param>
        /// <param name="actionName">ActionName 属性的初始值。</param>
        /// <param name="subTime">SubTime 属性的初始值。</param>
        /// <param name="actionType">ActionType 属性的初始值。</param>
        /// <param name="delFlag">DelFlag 属性的初始值。</param>
        public static SysAction CreateSysAction(global::System.Int32 actionID, global::System.String requestUrl, global::System.String requestHttpType, global::System.String actionName, global::System.DateTime subTime, global::System.Int32 actionType, global::System.Int32 delFlag)
        {
            SysAction sysAction = new SysAction();
            sysAction.ActionID = actionID;
            sysAction.RequestUrl = requestUrl;
            sysAction.RequestHttpType = requestHttpType;
            sysAction.ActionName = actionName;
            sysAction.SubTime = subTime;
            sysAction.ActionType = actionType;
            sysAction.DelFlag = delFlag;
            return sysAction;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActionID
        {
            get
            {
                return _ActionID;
            }
            set
            {
                if (_ActionID != value)
                {
                    OnActionIDChanging(value);
                    ReportPropertyChanging("ActionID");
                    _ActionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ActionID");
                    OnActionIDChanged();
                }
            }
        }
        private global::System.Int32 _ActionID;
        partial void OnActionIDChanging(global::System.Int32 value);
        partial void OnActionIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RequestUrl
        {
            get
            {
                return _RequestUrl;
            }
            set
            {
                OnRequestUrlChanging(value);
                ReportPropertyChanging("RequestUrl");
                _RequestUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RequestUrl");
                OnRequestUrlChanged();
            }
        }
        private global::System.String _RequestUrl;
        partial void OnRequestUrlChanging(global::System.String value);
        partial void OnRequestUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RequestHttpType
        {
            get
            {
                return _RequestHttpType;
            }
            set
            {
                OnRequestHttpTypeChanging(value);
                ReportPropertyChanging("RequestHttpType");
                _RequestHttpType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RequestHttpType");
                OnRequestHttpTypeChanged();
            }
        }
        private global::System.String _RequestHttpType;
        partial void OnRequestHttpTypeChanging(global::System.String value);
        partial void OnRequestHttpTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ActionName
        {
            get
            {
                return _ActionName;
            }
            set
            {
                OnActionNameChanging(value);
                ReportPropertyChanging("ActionName");
                _ActionName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ActionName");
                OnActionNameChanged();
            }
        }
        private global::System.String _ActionName;
        partial void OnActionNameChanging(global::System.String value);
        partial void OnActionNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SubTime
        {
            get
            {
                return _SubTime;
            }
            set
            {
                OnSubTimeChanging(value);
                ReportPropertyChanging("SubTime");
                _SubTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SubTime");
                OnSubTimeChanged();
            }
        }
        private global::System.DateTime _SubTime;
        partial void OnSubTimeChanging(global::System.DateTime value);
        partial void OnSubTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActionType
        {
            get
            {
                return _ActionType;
            }
            set
            {
                OnActionTypeChanging(value);
                ReportPropertyChanging("ActionType");
                _ActionType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActionType");
                OnActionTypeChanged();
            }
        }
        private global::System.Int32 _ActionType;
        partial void OnActionTypeChanging(global::System.Int32 value);
        partial void OnActionTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DelFlag
        {
            get
            {
                return _DelFlag;
            }
            set
            {
                OnDelFlagChanging(value);
                ReportPropertyChanging("DelFlag");
                _DelFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DelFlag");
                OnDelFlagChanged();
            }
        }
        private global::System.Int32 _DelFlag;
        partial void OnDelFlagChanging(global::System.Int32 value);
        partial void OnDelFlagChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DrisionMVCFrameModel", "FK_Sys_R_Role_Action_SysAction", "Sys_R_Role_Action")]
        public EntityCollection<Sys_R_Role_Action> Sys_R_Role_Action
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Sys_R_Role_Action>("DrisionMVCFrameModel.FK_Sys_R_Role_Action_SysAction", "Sys_R_Role_Action");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Sys_R_Role_Action>("DrisionMVCFrameModel.FK_Sys_R_Role_Action_SysAction", "Sys_R_Role_Action", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DrisionMVCFrameModel", "FK_Sys_R_User_Action_SysAction", "Sys_R_User_Action")]
        public EntityCollection<Sys_R_User_Action> Sys_R_User_Action
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Sys_R_User_Action>("DrisionMVCFrameModel.FK_Sys_R_User_Action_SysAction", "Sys_R_User_Action");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Sys_R_User_Action>("DrisionMVCFrameModel.FK_Sys_R_User_Action_SysAction", "Sys_R_User_Action", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DrisionMVCFrameModel", Name="SysGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SysGroup : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SysGroup 对象。
        /// </summary>
        /// <param name="groupID">GroupID 属性的初始值。</param>
        /// <param name="groupName">GroupName 属性的初始值。</param>
        /// <param name="groupOrder">GroupOrder 属性的初始值。</param>
        /// <param name="groupType">GroupType 属性的初始值。</param>
        /// <param name="delFlag">DelFlag 属性的初始值。</param>
        public static SysGroup CreateSysGroup(global::System.Int32 groupID, global::System.String groupName, global::System.Int32 groupOrder, global::System.Int32 groupType, global::System.Int32 delFlag)
        {
            SysGroup sysGroup = new SysGroup();
            sysGroup.GroupID = groupID;
            sysGroup.GroupName = groupName;
            sysGroup.GroupOrder = groupOrder;
            sysGroup.GroupType = groupType;
            sysGroup.DelFlag = delFlag;
            return sysGroup;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                if (_GroupID != value)
                {
                    OnGroupIDChanging(value);
                    ReportPropertyChanging("GroupID");
                    _GroupID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GroupID");
                    OnGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GroupName
        {
            get
            {
                return _GroupName;
            }
            set
            {
                OnGroupNameChanging(value);
                ReportPropertyChanging("GroupName");
                _GroupName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GroupName");
                OnGroupNameChanged();
            }
        }
        private global::System.String _GroupName;
        partial void OnGroupNameChanging(global::System.String value);
        partial void OnGroupNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupOrder
        {
            get
            {
                return _GroupOrder;
            }
            set
            {
                OnGroupOrderChanging(value);
                ReportPropertyChanging("GroupOrder");
                _GroupOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupOrder");
                OnGroupOrderChanged();
            }
        }
        private global::System.Int32 _GroupOrder;
        partial void OnGroupOrderChanging(global::System.Int32 value);
        partial void OnGroupOrderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GroupDescription
        {
            get
            {
                return _GroupDescription;
            }
            set
            {
                OnGroupDescriptionChanging(value);
                ReportPropertyChanging("GroupDescription");
                _GroupDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GroupDescription");
                OnGroupDescriptionChanged();
            }
        }
        private global::System.String _GroupDescription;
        partial void OnGroupDescriptionChanging(global::System.String value);
        partial void OnGroupDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupType
        {
            get
            {
                return _GroupType;
            }
            set
            {
                OnGroupTypeChanging(value);
                ReportPropertyChanging("GroupType");
                _GroupType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupType");
                OnGroupTypeChanged();
            }
        }
        private global::System.Int32 _GroupType;
        partial void OnGroupTypeChanging(global::System.Int32 value);
        partial void OnGroupTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DelFlag
        {
            get
            {
                return _DelFlag;
            }
            set
            {
                OnDelFlagChanging(value);
                ReportPropertyChanging("DelFlag");
                _DelFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DelFlag");
                OnDelFlagChanged();
            }
        }
        private global::System.Int32 _DelFlag;
        partial void OnDelFlagChanging(global::System.Int32 value);
        partial void OnDelFlagChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DrisionMVCFrameModel", Name="SysRole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SysRole : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SysRole 对象。
        /// </summary>
        /// <param name="roleID">RoleID 属性的初始值。</param>
        /// <param name="roleName">RoleName 属性的初始值。</param>
        /// <param name="roleOrder">RoleOrder 属性的初始值。</param>
        /// <param name="delFlag">DelFlag 属性的初始值。</param>
        public static SysRole CreateSysRole(global::System.Int32 roleID, global::System.String roleName, global::System.Int32 roleOrder, global::System.Int32 delFlag)
        {
            SysRole sysRole = new SysRole();
            sysRole.RoleID = roleID;
            sysRole.RoleName = roleName;
            sysRole.RoleOrder = roleOrder;
            sysRole.DelFlag = delFlag;
            return sysRole;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                if (_RoleID != value)
                {
                    OnRoleIDChanging(value);
                    ReportPropertyChanging("RoleID");
                    _RoleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleID");
                    OnRoleIDChanged();
                }
            }
        }
        private global::System.Int32 _RoleID;
        partial void OnRoleIDChanging(global::System.Int32 value);
        partial void OnRoleIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoleDescription
        {
            get
            {
                return _RoleDescription;
            }
            set
            {
                OnRoleDescriptionChanging(value);
                ReportPropertyChanging("RoleDescription");
                _RoleDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoleDescription");
                OnRoleDescriptionChanged();
            }
        }
        private global::System.String _RoleDescription;
        partial void OnRoleDescriptionChanging(global::System.String value);
        partial void OnRoleDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleOrder
        {
            get
            {
                return _RoleOrder;
            }
            set
            {
                OnRoleOrderChanging(value);
                ReportPropertyChanging("RoleOrder");
                _RoleOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleOrder");
                OnRoleOrderChanged();
            }
        }
        private global::System.Int32 _RoleOrder;
        partial void OnRoleOrderChanging(global::System.Int32 value);
        partial void OnRoleOrderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DelFlag
        {
            get
            {
                return _DelFlag;
            }
            set
            {
                OnDelFlagChanging(value);
                ReportPropertyChanging("DelFlag");
                _DelFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DelFlag");
                OnDelFlagChanged();
            }
        }
        private global::System.Int32 _DelFlag;
        partial void OnDelFlagChanging(global::System.Int32 value);
        partial void OnDelFlagChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DrisionMVCFrameModel", "FK_Sys_R_Role_Action_SysRole", "Sys_R_Role_Action")]
        public EntityCollection<Sys_R_Role_Action> Sys_R_Role_Action
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Sys_R_Role_Action>("DrisionMVCFrameModel.FK_Sys_R_Role_Action_SysRole", "Sys_R_Role_Action");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Sys_R_Role_Action>("DrisionMVCFrameModel.FK_Sys_R_Role_Action_SysRole", "Sys_R_Role_Action", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DrisionMVCFrameModel", "FK_Sys_R_User_Role_SysRole", "Sys_R_User_Role")]
        public EntityCollection<Sys_R_User_Role> Sys_R_User_Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Sys_R_User_Role>("DrisionMVCFrameModel.FK_Sys_R_User_Role_SysRole", "Sys_R_User_Role");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Sys_R_User_Role>("DrisionMVCFrameModel.FK_Sys_R_User_Role_SysRole", "Sys_R_User_Role", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DrisionMVCFrameModel", Name="SysUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SysUser : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SysUser 对象。
        /// </summary>
        /// <param name="userID">UserID 属性的初始值。</param>
        /// <param name="userName">UserName 属性的初始值。</param>
        /// <param name="nickName">NickName 属性的初始值。</param>
        /// <param name="password">Password 属性的初始值。</param>
        /// <param name="createTime">CreateTime 属性的初始值。</param>
        /// <param name="delFlag">DelFlag 属性的初始值。</param>
        public static SysUser CreateSysUser(global::System.Int32 userID, global::System.String userName, global::System.String nickName, global::System.String password, global::System.DateTime createTime, global::System.Int32 delFlag)
        {
            SysUser sysUser = new SysUser();
            sysUser.UserID = userID;
            sysUser.UserName = userName;
            sysUser.NickName = nickName;
            sysUser.Password = password;
            sysUser.CreateTime = createTime;
            sysUser.DelFlag = delFlag;
            return sysUser;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NickName
        {
            get
            {
                return _NickName;
            }
            set
            {
                OnNickNameChanging(value);
                ReportPropertyChanging("NickName");
                _NickName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NickName");
                OnNickNameChanged();
            }
        }
        private global::System.String _NickName;
        partial void OnNickNameChanging(global::System.String value);
        partial void OnNickNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private global::System.DateTime _CreateTime;
        partial void OnCreateTimeChanging(global::System.DateTime value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLoginTime
        {
            get
            {
                return _LastLoginTime;
            }
            set
            {
                OnLastLoginTimeChanging(value);
                ReportPropertyChanging("LastLoginTime");
                _LastLoginTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLoginTime");
                OnLastLoginTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLoginTime;
        partial void OnLastLoginTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DelFlag
        {
            get
            {
                return _DelFlag;
            }
            set
            {
                OnDelFlagChanging(value);
                ReportPropertyChanging("DelFlag");
                _DelFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DelFlag");
                OnDelFlagChanged();
            }
        }
        private global::System.Int32 _DelFlag;
        partial void OnDelFlagChanging(global::System.Int32 value);
        partial void OnDelFlagChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DrisionMVCFrameModel", "FK_Sys_R_User_Action_SysUser", "Sys_R_User_Action")]
        public EntityCollection<Sys_R_User_Action> Sys_R_User_Action
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Sys_R_User_Action>("DrisionMVCFrameModel.FK_Sys_R_User_Action_SysUser", "Sys_R_User_Action");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Sys_R_User_Action>("DrisionMVCFrameModel.FK_Sys_R_User_Action_SysUser", "Sys_R_User_Action", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DrisionMVCFrameModel", "FK_Sys_R_User_Role_SysUser", "Sys_R_User_Role")]
        public EntityCollection<Sys_R_User_Role> Sys_R_User_Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Sys_R_User_Role>("DrisionMVCFrameModel.FK_Sys_R_User_Role_SysUser", "Sys_R_User_Role");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Sys_R_User_Role>("DrisionMVCFrameModel.FK_Sys_R_User_Role_SysUser", "Sys_R_User_Role", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
